
version: "3.4"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    ports:
      - "32400:32400"
      - "1900:1900"
      - "3005:3005"
      - "5353:5353"
      - "8324:8324"
      - "32410:32410"
      - "32412:32412"
      - "32413:32413"
      - "32414:32414"
      - "32469:32469"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= claim-oRHxJvUMMiRD9YkFe51y    #opcional, se puede obtener aqui https://www.plex.tv/claim/
    volumes:
      - plex_data:/config
      - /media/plexstorage:/media                 #montamos la carpeta remota donde esta nuestro contenido en el contenedor
    restart: always
  
volumes:
  plex_data:
