  plex:
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - plex_data:/config
      - /media/plexstorage:/media         #montamos la carpeta remota donde esta nuestro contenido en el contenedor
    restart: always
    image: linuxserver/plex

volumes:
  plex_data: